# tmux起動時のシェルをzshにする
set-option -g default-shell /bin/zsh

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# prefixキーをC-qに変更
set -g prefix C-q

# C-bのキーバインドを解除
unbind C-b

# ステータスバーをトップに配置する
set-option -g status-position top

# 左右のステータスバーの長さを決定する
set-option -g status-left-length 90
set-option -g status-right-length 90

# #P => ペイン番号
# 最左に表示
set-option -g status-left '#H:[#P]'

# Wi-Fi、バッテリー残量、現在時刻
# 最右に表示
set-option -g status-right "#(ifconfig en0 | grep -q 'status: active' && echo 📶 || echo ❌) #(pmset -g batt | awk 'NR==2 {gsub(\";\",\"\"); print $3}') [%Y-%m-%d(%a) %H:%M]"

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# センタライズ（主にウィンドウ番号など）
set-option -g status-justify centre

# デフォルトエディタをnanoにする（新規ペインに伝播）
set-environment -g EDITOR nano
set-environment -g VISUAL nano

# ペイン境界にタイトルを表示する（6ペインスクリプトで設定したタイトル用）
set-option -g pane-border-status top
set-option -g pane-border-format " #P #T "

# ステータスバーの色を設定する
set-option -g status-bg "colour238"

# status line の文字色を指定する。
set-option -g status-fg "colour255"

# | でペインを縦分割する
bind | split-window -h

# - でペインを縦分割する
bind - split-window -v

# マウス操作を有効にする
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"


# copy on
set -g set-clipboard on
set -s copy-command 'pbcopy'

# マウスドラッグ選択後にpbcopyに送る
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'